### PR TITLE
Preservation dev

### PR DESCRIPTION
**Pull request by jolf**
Added handling of preservationUpdates, extraction of characterization tools used, and created a view for the FITS metadata for content files.
Also thoroughly testing the preservation methods on both Instance and ContentFile.

### CODE REVIEW

**Comment by davidgrove73** [comment]
:+1:

**Comment by O-Zone** [comment]
"All checks have failed" is not something we worry too much about, I recon? :-O

**Comment by jolf** [comment]
@O-Zone It is the same errors we get on all other branches and all other commits. It is only clearly visible, since it this a pull-request.
It would be beneficial to our common development environment, if we could fix our travis setup, so the tests wouldn't fail, but alas it has not been prioritized.

**Comment by O-Zone** [comment]
Thought so! Was just checking! :-) :+1:

**Comment by jolf** [comment]
Apparently the development branch have moved beyond merging with this pull request.
I will get this branch up-to-date with the development branch, and make a new pull-request.

**Pull request merged**
